language: objective-c
os: osx
osx_image: xcode9.4
branches:
  only:
  - travis

script:
  - HOMEBREW_NO_AUTO_UPDATE=1 brew install clickhouse.rb
  - brew link --overwrite gcc
  - brew test clickhouse.rb